SYSTEMC_HOME=/usr/local/systemc-2.3.3
TARGET_ARCH=linux64
include ./Makefile.config

PROJECT = tb

INCDIR = \
	-I./

OBJS = \
	$(PROJECT).o \
	top.o \
	master.o \
	slave.o 

include ./Makefile.rules

# DO NOT DELETE
